### ISSUE TITLE
logging.debug(f"Calling function check_outdir")

### ISSUE THREAD

**Issue by liuqian666** [boasvdp/extract_genes_ABRicate#6]
hello！
I was using `extract_genes_ABRicate` to extract eae genes from genomes
but it shows that :
`logging.debug(f"Calling function check_outdir")`
<img width="1253" alt="图片" src="https://user-images.githubusercontent.com/57260099/192073174-dd6c10a1-a8b8-4933-bbb9-daf7322b1ec7.png">

Is there any thing wrong with my code?

**Comment by boasvdp** [comment]
Hi,
Can I ask which version of Python you are using? You can test this by running `python -V` while the `env_extract_genes_ABRicate` environment is activated.

Judging by the error, it seems that using an f-string (https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) gives a problem. These were introduced in Python 3.6. I will update the conda environment file so that the right Python version is installed for future users.

Thanks,
Boas

**Comment by boasvdp** [comment]
Added `python>=3.6` to conda env file in https://github.com/boasvdp/extract_genes_ABRicate/commit/24b3b4a4c2779afb814a27c972e8e76035d84c3d

**Comment by liuqian666** [comment]
> Added `python>=3.6` to conda env file in [24b3b4a](https://github.com/boasvdp/extract_genes_ABRicate/commit/24b3b4a4c2779afb814a27c972e8e76035d84c3d)

Got it!
Thank you very much!☺︎

**Comment by boasvdp** [comment]
Is it working for you now?

**Comment by liuqian666** [comment]
Yes!
